version: '2'
services:
  php70-apache:
    image: lucasapoena/docker-magento2:php7.0
    ports:
      - "8070:80" # web
      - "9070:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - <project_name>-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=10.254.254.254 remote_connect_back=0"      
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: "America/Fortaleza"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network

  php71-apache:
    image: lucasapoena/docker-magento2:php7.1
    ports:
      - "8071:80" # web
      - "9071:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - <project_name>-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=10.254.254.254 remote_connect_back=0"      
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: "America/Fortaleza"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network
  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <project_name>-network
  php72-apache:
    image: lucasapoena/docker-magento2:php7.2
    ports:
      - "8072:80" # web
      - "9072:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - <project_name>-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=10.254.254.254 remote_connect_back=0"      
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: "America/Fortaleza"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network
      
  db:
    image: mariadb
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <project_name>-network    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  <project_name>-sync:
    external: true
  dbdata:
    driver: local
